-- Load the user-level table generated by Python/Pandas.
DROP TABLE IF EXISTS user_growth_profile;
CREATE TABLE user_growth_profile(
msno VARCHAR(64) NOT NULL PRIMARY KEY,registration_date DATE NOT NULL,
registered_via SMALLINT NULL,activated_flag TINYINT NULL,d1_retained TINYINT NULL,
d3_retained TINYINT NULL,d7_retained TINYINT NULL,first_7_active_days SMALLINT NULL,
first_7_play_count BIGINT NULL,first_7_total_secs DOUBLE NULL,
activation_eligible_flag TINYINT NOT NULL,d1_eligible_flag TINYINT NOT NULL,
d3_eligible_flag TINYINT NOT NULL,d7_eligible_flag TINYINT NOT NULL,
first_7_eligible_flag TINYINT NOT NULL,data_as_of_date DATE NOT NULL,
INDEX idx_date(registration_date),INDEX idx_source_date(registered_via,registration_date));
LOAD DATA LOCAL INFILE 'data/processed/user_growth_profile.csv'
INTO TABLE user_growth_profile CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES
(msno,registration_date,@via,@a,@d1,@d3,@d7,@days,@plays,@secs,
activation_eligible_flag,d1_eligible_flag,d3_eligible_flag,d7_eligible_flag,
first_7_eligible_flag,@as_of)
SET registered_via=NULLIF(@via,''),activated_flag=NULLIF(@a,''),
d1_retained=NULLIF(@d1,''),d3_retained=NULLIF(@d3,''),d7_retained=NULLIF(@d7,''),
first_7_active_days=NULLIF(@days,''),first_7_play_count=NULLIF(@plays,''),
first_7_total_secs=NULLIF(@secs,''),
data_as_of_date=STR_TO_DATE(TRIM(TRAILING '\r' FROM @as_of),'%Y-%m-%d');
SELECT COUNT(*) rows_n,COUNT(DISTINCT msno) users_n,MIN(registration_date) min_date,
MAX(registration_date) max_date,MIN(data_as_of_date) min_as_of,
MAX(data_as_of_date) max_as_of FROM user_growth_profile;
SELECT SUM(d1_eligible_flag=0 AND d1_retained IS NOT NULL) invalid_d1,
SUM(d3_eligible_flag=0 AND d3_retained IS NOT NULL) invalid_d3,
SUM(d7_eligible_flag=0 AND d7_retained IS NOT NULL) invalid_d7,
SUM(first_7_eligible_flag=0 AND first_7_active_days IS NOT NULL) invalid_first_week
FROM user_growth_profile;
